import type { AgentActionDefinition } from './agent-action.types';

export const AGENT_ACTION_DEFINITIONS: AgentActionDefinition[] = [
  {
    id: 'ai.auto_reply.enable',
    title: 'Enable AI auto reply',
    description: 'Turn on AI auto reply across sessions',
    category: 'ai',
    aliases: ['washa ai auto reply', 'enable ai auto reply', 'turn on ai replies', 'washa auto reply'],
    keywords: ['washa', 'enable', 'auto', 'reply', 'ai'],
    risk: 'safe',
    requiredPermission: 'manage_ai_settings',
    requiresConfirmation: false,
    supportsDirectExecution: true,
    settingsPanelId: 'ai-auto-reply',
  },
  {
    id: 'ai.auto_reply.disable',
    title: 'Disable AI auto reply',
    description: 'Turn off AI auto reply',
    category: 'ai',
    aliases: ['zima ai auto reply', 'disable ai auto reply', 'stop ai replies', 'zima auto reply'],
    keywords: ['zima', 'disable', 'stop', 'auto', 'reply', 'ai'],
    risk: 'safe',
    requiredPermission: 'manage_ai_settings',
    requiresConfirmation: false,
    supportsDirectExecution: true,
    settingsPanelId: 'ai-auto-reply',
  },
  {
    id: 'ai.reply_style.fast',
    title: 'Fast AI reply style',
    description: 'Make AI reply faster',
    category: 'ai',
    aliases: ['fanya ai ijibu faster', 'make ai reply faster', 'speed up ai replies', 'ai haraka'],
    keywords: ['fast', 'faster', 'haraka', 'speed', 'reply'],
    risk: 'safe',
    requiredPermission: 'manage_ai_settings',
    requiresConfirmation: false,
    supportsDirectExecution: true,
    settingsPanelId: 'ai-auto-reply',
  },
  {
    id: 'ai.reply_style.balanced',
    title: 'Balanced AI reply style',
    description: 'Set balanced human timing',
    category: 'ai',
    aliases: ['weka ai balanced', 'make ai balanced', 'balanced reply'],
    keywords: ['balanced', 'balance', 'reply'],
    risk: 'safe',
    requiredPermission: 'manage_ai_settings',
    requiresConfirmation: false,
    supportsDirectExecution: true,
    settingsPanelId: 'ai-auto-reply',
  },
  {
    id: 'ai.reply_style.careful',
    title: 'Careful AI reply style',
    description: 'Set careful human timing',
    category: 'ai',
    aliases: ['fanya ai iwe careful', 'make ai careful', 'polepole ai'],
    keywords: ['careful', 'polepole', 'slow'],
    risk: 'safe',
    requiredPermission: 'manage_ai_settings',
    requiresConfirmation: false,
    supportsDirectExecution: true,
    settingsPanelId: 'ai-auto-reply',
  },
  {
    id: 'ai.burst_reading.enable',
    title: 'Enable burst message reading',
    description: 'AI reads burst messages together',
    category: 'ai',
    aliases: ['washa burst message reading', 'washa burst reading', 'ai isome message zote pamoja'],
    keywords: ['burst', 'reading', 'washa', 'pamoja'],
    risk: 'safe',
    requiredPermission: 'manage_ai_settings',
    requiresConfirmation: false,
    supportsDirectExecution: true,
    settingsPanelId: 'ai-auto-reply',
  },
  {
    id: 'ai.burst_reading.disable',
    title: 'Disable burst message reading',
    description: 'AI may reply to messages separately',
    category: 'ai',
    aliases: ['zima burst reading', 'zima burst message reading'],
    keywords: ['burst', 'reading', 'zima'],
    risk: 'medium',
    requiredPermission: 'manage_ai_settings',
    requiresConfirmation: true,
    supportsDirectExecution: true,
    warningMessage: 'Hii inaweza kufanya AI ijibu kila ujumbe tofauti.',
    settingsPanelId: 'ai-auto-reply',
  },
  {
    id: 'ai.presence_replies.enable',
    title: 'Enable presence replies',
    description: 'AI replies when customer asks if online',
    category: 'ai',
    aliases: ['washa presence replies', 'ai ijibu upo online'],
    keywords: ['presence', 'online', 'washa'],
    risk: 'safe',
    requiredPermission: 'manage_ai_settings',
    requiresConfirmation: false,
    supportsDirectExecution: true,
    settingsPanelId: 'ai-auto-reply',
  },
  {
    id: 'ai.quoted_reply.enable',
    title: 'Enable quoted reply',
    description: 'AI replies using message quote',
    category: 'ai',
    aliases: ['washa quoted reply', 'ai ijibu kwa reply ya message'],
    keywords: ['quoted', 'reply', 'washa'],
    risk: 'safe',
    requiredPermission: 'manage_ai_settings',
    requiresConfirmation: false,
    supportsDirectExecution: true,
    settingsPanelId: 'ai-auto-reply',
  },
  {
    id: 'ai.quoted_reply.disable',
    title: 'Disable quoted reply',
    description: 'Turn off quoted replies',
    category: 'ai',
    aliases: ['zima quoted reply', 'disable quoted reply'],
    keywords: ['quoted', 'reply', 'zima'],
    risk: 'safe',
    requiredPermission: 'manage_ai_settings',
    requiresConfirmation: false,
    supportsDirectExecution: true,
    settingsPanelId: 'ai-auto-reply',
  },
  {
    id: 'ai.suspicious_name_confirmation.enable',
    title: 'Enable suspicious name check',
    description: 'Confirm suspicious customer names',
    category: 'ai',
    aliases: ['washa suspicious name check', 'hakikisha jina lina confirm'],
    keywords: ['suspicious', 'name', 'confirm'],
    risk: 'safe',
    requiredPermission: 'manage_ai_settings',
    requiresConfirmation: false,
    supportsDirectExecution: true,
    settingsPanelId: 'ai-auto-reply',
  },
  {
    id: 'ai.knowledge.reindex',
    title: 'Reindex AI knowledge',
    description: 'Refresh shop knowledge index',
    category: 'ai',
    aliases: ['reindex ai knowledge', 'refresh shop knowledge', 'update ai knowledge', 'reindex knowledge'],
    keywords: ['reindex', 'knowledge', 'refresh'],
    risk: 'safe',
    requiredPermission: 'manage_ai_settings',
    requiresConfirmation: false,
    supportsDirectExecution: true,
    settingsPanelId: 'ai-knowledge',
  },
  {
    id: 'ai.memory.clear',
    title: 'Clear AI memory',
    description: 'Clear staff AI memory files',
    category: 'data',
    aliases: ['clear ai memory', 'futa ai memory'],
    keywords: ['clear', 'memory', 'futa'],
    risk: 'high',
    requiredPermission: 'manage_system',
    requiresConfirmation: true,
    supportsDirectExecution: true,
    adminOnly: true,
    warningMessage: 'Hii itafuta AI memory files. Unataka niendelee?',
    settingsPanelId: 'ai-memory',
  },
  {
    id: 'ai.provider.change',
    title: 'Change AI provider',
    description: 'Change AI model/provider',
    category: 'ai',
    aliases: ['change ai provider', 'badilisha model', 'change model'],
    keywords: ['provider', 'model', 'change'],
    risk: 'high',
    requiredPermission: 'manage_ai_settings',
    requiresConfirmation: true,
    supportsDirectExecution: false,
    adminOnly: true,
    settingsPanelId: 'ai',
  },
  {
    id: 'whatsapp.qr.open',
    title: 'Show WhatsApp QR',
    description: 'Open WhatsApp accounts to scan QR',
    category: 'whatsapp',
    aliases: ['onyesha qr', 'fungua qr ya whatsapp', 'scan whatsapp', 'onyesha qr ya whatsapp'],
    keywords: ['qr', 'whatsapp', 'scan', 'onyesha'],
    risk: 'safe',
    requiredPermission: 'manage_whatsapp_channels',
    requiresConfirmation: false,
    supportsDirectExecution: false,
    settingsPanelId: 'whatsapp-accounts',
  },
  {
    id: 'whatsapp.session.reconnect',
    title: 'Reconnect WhatsApp',
    description: 'Restart WhatsApp session',
    category: 'whatsapp',
    aliases: ['reconnect whatsapp', 'restart whatsapp session'],
    keywords: ['reconnect', 'restart', 'whatsapp'],
    risk: 'medium',
    requiredPermission: 'manage_whatsapp_channels',
    requiresConfirmation: true,
    supportsDirectExecution: true,
    warningMessage: 'Hii ita-restart WhatsApp session.',
  },
  {
    id: 'whatsapp.session.remove',
    title: 'Remove WhatsApp session',
    description: 'Delete WhatsApp session',
    category: 'whatsapp',
    aliases: ['remove whatsapp session', 'delete whatsapp account', 'futa whatsapp'],
    keywords: ['remove', 'delete', 'whatsapp', 'futa'],
    risk: 'high',
    requiredPermission: 'manage_whatsapp_channels',
    requiresConfirmation: true,
    supportsDirectExecution: true,
    adminOnly: true,
    warningMessage: 'Hii itafuta WhatsApp session kabisa.',
  },
  {
    id: 'whatsapp.safety.enable',
    title: 'Enable WhatsApp safety guard',
    description: 'Turn on WhatsApp safety',
    category: 'whatsapp',
    aliases: ['washa safety guard', 'enable whatsapp safety', 'washa whatsapp safety'],
    keywords: ['safety', 'guard', 'washa'],
    risk: 'safe',
    requiredPermission: 'manage_whatsapp_safety',
    requiresConfirmation: false,
    supportsDirectExecution: true,
    settingsPanelId: 'whatsapp-safety',
  },
  {
    id: 'whatsapp.safety.disable',
    title: 'Disable WhatsApp safety guard',
    description: 'Turn off WhatsApp safety',
    category: 'whatsapp',
    aliases: ['zima safety guard', 'disable whatsapp safety', 'zima whatsapp safety'],
    keywords: ['safety', 'guard', 'zima', 'disable'],
    risk: 'high',
    requiredPermission: 'manage_whatsapp_safety',
    requiresConfirmation: true,
    supportsDirectExecution: true,
    adminOnly: true,
    warningMessage: 'Hii ni risky kwa sababu inaweza kuongeza ban risk ya WhatsApp.',
    settingsPanelId: 'whatsapp-safety',
  },
  {
    id: 'whatsapp.campaigns.pause',
    title: 'Pause campaigns',
    description: 'Disable WhatsApp campaigns',
    category: 'campaign',
    aliases: ['pause campaigns', 'simamisha campaigns', 'zima campaigns'],
    keywords: ['pause', 'campaigns', 'simamisha'],
    risk: 'safe',
    requiredPermission: 'manage_campaigns',
    requiresConfirmation: false,
    supportsDirectExecution: true,
  },
  {
    id: 'whatsapp.campaigns.resume',
    title: 'Resume campaigns',
    description: 'Enable WhatsApp campaigns',
    category: 'campaign',
    aliases: ['resume campaigns', 'endeleza campaigns', 'washa campaigns'],
    keywords: ['resume', 'campaigns', 'endeleza'],
    risk: 'medium',
    requiredPermission: 'manage_campaigns',
    requiresConfirmation: true,
    supportsDirectExecution: true,
    warningMessage: 'Endeleza campaigns inaweza kuongeza sending risk.',
  },
  {
    id: 'followup.autopilot.enable',
    title: 'Enable follow-up autopilot',
    description: 'Turn on follow-up autopilot',
    category: 'followup',
    aliases: ['washa follow-up autopilot', 'enable follow-up autopilot', 'washa followup autopilot'],
    keywords: ['followup', 'autopilot', 'washa'],
    risk: 'medium',
    requiredPermission: 'manage_followups',
    requiresConfirmation: true,
    supportsDirectExecution: true,
    warningMessage: 'Autopilot itatuma follow-ups kiotomatiki.',
  },
  {
    id: 'followup.autopilot.disable',
    title: 'Disable follow-up autopilot',
    description: 'Turn off follow-up autopilot',
    category: 'followup',
    aliases: ['zima follow-up autopilot', 'disable followup autopilot', 'zima followup autopilot'],
    keywords: ['followup', 'autopilot', 'zima'],
    risk: 'safe',
    requiredPermission: 'manage_followups',
    requiresConfirmation: false,
    supportsDirectExecution: true,
  },
  {
    id: 'followup.create_for_current_customer',
    title: 'Create follow-up for customer',
    description: 'Schedule follow-up for current customer',
    category: 'followup',
    aliases: ['create follow-up', 'nikumbushe kumfuatilia huyu customer', 'weka follow-up', 'weka followup'],
    keywords: ['followup', 'create', 'customer', 'weka'],
    risk: 'safe',
    requiredPermission: 'manage_followups',
    requiresConfirmation: false,
    supportsDirectExecution: true,
  },
  {
    id: 'followup.rules.open',
    title: 'Open follow-up rules',
    description: 'Navigate to follow-up rules',
    category: 'followup',
    aliases: ['open follow-up rules', 'badilisha follow-up rules'],
    keywords: ['followup', 'rules', 'open'],
    risk: 'safe',
    requiredPermission: 'manage_followups',
    requiresConfirmation: false,
    supportsDirectExecution: false,
    settingsPanelId: 'followup-rules',
  },
  {
    id: 'branch.switch',
    title: 'Switch branch',
    description: 'Switch active branch',
    category: 'branch',
    aliases: ['badilisha branch', 'switch branch', 'change branch'],
    keywords: ['branch', 'badilisha', 'switch', 'arusha', 'dar'],
    risk: 'safe',
    requiredPermission: 'manage_business_settings',
    requiresConfirmation: false,
    supportsDirectExecution: true,
    settingsPanelId: 'ai-branch-profile',
  },
  {
    id: 'payment.settings.open',
    title: 'Open payment settings',
    description: 'Navigate to payment accounts',
    category: 'business',
    aliases: ['badilisha payment details', 'open payment accounts', 'open payment settings'],
    keywords: ['payment', 'accounts', 'badilisha', 'open'],
    risk: 'medium',
    requiredPermission: 'manage_payment_settings',
    requiresConfirmation: false,
    supportsDirectExecution: false,
    settingsPanelId: 'ai-branch-profile',
  },
  {
    id: 'payment.details.update',
    title: 'Update payment details',
    description: 'Update payment account',
    category: 'business',
    aliases: ['change payment account', 'update payment number'],
    keywords: ['payment', 'update', 'change'],
    risk: 'high',
    requiredPermission: 'manage_payment_settings',
    requiresConfirmation: true,
    supportsDirectExecution: false,
    adminOnly: true,
    settingsPanelId: 'ai-branch-profile',
  },
  {
    id: 'products.open',
    title: 'Open products',
    description: 'Navigate to products',
    category: 'business',
    aliases: ['open products', 'nionyeshe products settings'],
    keywords: ['products', 'open'],
    risk: 'safe',
    requiresConfirmation: false,
    supportsDirectExecution: false,
    settingsPanelId: 'products',
  },
  {
    id: 'installment.rules.open',
    title: 'Open installment rules',
    description: 'Navigate to installment rules',
    category: 'business',
    aliases: ['open installment rules', 'badilisha installment rules'],
    keywords: ['installment', 'rules'],
    risk: 'safe',
    requiresConfirmation: false,
    supportsDirectExecution: false,
    settingsPanelId: 'ai-branch-profile',
  },
  {
    id: 'app.health.check',
    title: 'Check app health',
    description: 'Read app health status',
    category: 'health',
    aliases: ['check app health', 'system iko sawa', 'why app not working'],
    keywords: ['health', 'status', 'sawa'],
    risk: 'safe',
    requiredPermission: 'view_app_health',
    requiresConfirmation: false,
    supportsDirectExecution: true,
  },
  {
    id: 'ai.reply.diagnose',
    title: 'Diagnose AI not replying',
    description: 'Check why AI is not replying',
    category: 'health',
    aliases: ['why ai is not replying', 'kwa nini ai haijibu', 'why ai delayed', 'ai haijibu'],
    keywords: ['ai', 'reply', 'haijibu', 'why'],
    risk: 'safe',
    requiredPermission: 'view_app_health',
    requiresConfirmation: false,
    supportsDirectExecution: true,
    settingsPanelId: 'ai-auto-reply',
  },
  {
    id: 'queue.retry_failed',
    title: 'Retry failed messages',
    description: 'Retry failed send queue items',
    category: 'system',
    aliases: ['retry failed messages', 'jaribu kutuma failed messages'],
    keywords: ['retry', 'failed', 'queue'],
    risk: 'medium',
    requiredPermission: 'manage_system',
    requiresConfirmation: true,
    supportsDirectExecution: true,
    adminOnly: true,
    warningMessage: 'Hii itajaribu kutuma messages zilizoshindwa tena.',
  },
  {
    id: 'logs.open',
    title: 'Open logs',
    description: 'Navigate to logs',
    category: 'system',
    aliases: ['open logs', 'show errors', 'onyesha logs'],
    keywords: ['logs', 'errors', 'open'],
    risk: 'safe',
    requiredPermission: 'view_logs',
    requiresConfirmation: false,
    supportsDirectExecution: false,
    settingsPanelId: 'logs',
  },
  {
    id: 'webhooks.open',
    title: 'Open webhooks',
    description: 'Navigate to webhooks settings',
    category: 'system',
    aliases: ['open webhooks', 'show webhooks', 'fungua webhooks'],
    keywords: ['webhooks', 'open', 'fungua'],
    risk: 'safe',
    requiredPermission: 'manage_system',
    requiresConfirmation: false,
    supportsDirectExecution: false,
    settingsPanelId: 'webhooks',
  },
  {
    id: 'plugins.open',
    title: 'Open plugins',
    description: 'Navigate to plugins settings',
    category: 'system',
    aliases: ['open plugins', 'show plugins', 'fungua plugins'],
    keywords: ['plugins', 'open', 'fungua'],
    risk: 'safe',
    requiredPermission: 'manage_system',
    requiresConfirmation: false,
    supportsDirectExecution: false,
    settingsPanelId: 'plugins',
  },
  {
    id: 'infrastructure.open',
    title: 'Open infrastructure',
    description: 'Navigate to infrastructure settings',
    category: 'system',
    aliases: ['open infrastructure', 'show infrastructure', 'fungua infrastructure'],
    keywords: ['infrastructure', 'server', 'open'],
    risk: 'safe',
    requiredPermission: 'manage_system',
    requiresConfirmation: false,
    supportsDirectExecution: false,
    settingsPanelId: 'infrastructure',
  },
  {
    id: 'api_keys.open',
    title: 'Open API keys',
    description: 'Navigate to service API keys',
    category: 'system',
    aliases: ['open api keys', 'manage api keys', 'fungua api keys'],
    keywords: ['api', 'keys', 'open'],
    risk: 'safe',
    requiredPermission: 'manage_system',
    requiresConfirmation: false,
    supportsDirectExecution: false,
    settingsPanelId: 'api-keys',
  },
  {
    id: 'backup.create',
    title: 'Create backup',
    description: 'Create data backup',
    category: 'system',
    aliases: ['create backup', 'backup data', 'fanya backup'],
    keywords: ['backup', 'create'],
    risk: 'medium',
    requiredPermission: 'manage_system',
    requiresConfirmation: true,
    supportsDirectExecution: true,
    adminOnly: true,
    warningMessage: 'Hii itaanza backup process.',
  },
  {
    id: 'data.export',
    title: 'Export customer data',
    description: 'Export customer data',
    category: 'data',
    aliases: ['export customer data', 'hamisha data ya wateja'],
    keywords: ['export', 'customer', 'data'],
    risk: 'high',
    requiredPermission: 'export_data',
    requiresConfirmation: true,
    supportsDirectExecution: false,
    adminOnly: true,
    warningMessage: 'Export data inahitaji idhini ya admin.',
    settingsPanelId: 'storage-backup',
  },
  {
    id: 'users.open',
    title: 'Open users',
    description: 'Navigate to users',
    category: 'system',
    aliases: ['open users', 'manage users'],
    keywords: ['users', 'roles', 'open'],
    risk: 'safe',
    requiredPermission: 'manage_users',
    requiresConfirmation: false,
    supportsDirectExecution: false,
    settingsPanelId: 'users',
  },
  {
    id: 'user.role.change',
    title: 'Change user role',
    description: 'Change user role',
    category: 'system',
    aliases: ['change role', 'make user admin', 'badilisha role'],
    keywords: ['role', 'admin', 'change'],
    risk: 'high',
    requiredPermission: 'manage_users',
    requiresConfirmation: true,
    supportsDirectExecution: false,
    adminOnly: true,
    settingsPanelId: 'users',
  },
  {
    id: 'db.raw_query',
    title: 'Raw database query',
    description: 'Blocked',
    category: 'system',
    aliases: ['run sql', 'database query', 'raw query'],
    keywords: ['sql', 'query', 'database'],
    risk: 'blocked',
    requiresConfirmation: false,
    supportsDirectExecution: false,
  },
  {
    id: 'ai.training.open',
    title: 'Open AI Training Center',
    description: 'Navigate to AI Training Center',
    category: 'ai',
    aliases: [
      'open training center',
      'fungua training center',
      'ai training',
      'pending training',
    ],
    keywords: ['training', 'learn', 'teach', 'center'],
    risk: 'safe',
    requiredPermission: 'manage_ai_settings',
    requiresConfirmation: false,
    supportsDirectExecution: false,
  },
  {
    id: 'ai.training.teach',
    title: 'Teach AI a rule',
    description: 'Create a training item from natural language instruction',
    category: 'ai',
    aliases: [
      'teach ai',
      'fundisha ai',
      'save this as learned rule',
      'ai ijifunze',
    ],
    keywords: ['teach', 'learn', 'rule', 'fundisha', 'training'],
    risk: 'medium',
    requiredPermission: 'manage_ai_settings',
    requiresConfirmation: true,
    supportsDirectExecution: false,
    warningMessage: 'Review and approve in Training Center before AI uses this globally.',
  },
];
