/** Default INAUZWA sync status for E2E mocks (matches backend shape). */
export const MOCK_INAUZWA_STATUS = {
  configured: false,
  database: false,
  api: false,
  branchId: null,
  vendorId: null,
  currency: 'TZS',
  defaultApiUrl: null,
  defaultSupabaseUrl: null,
  hasDefaultSupabaseAnonKey: false,
  lastSyncAt: null,
  lastSyncError: null,
  hasSupabaseConfig: false,
  preferences: {
    branchId: null,
    vendorId: null,
    autoSyncEnabled: false,
    autoSyncIntervalMinutes: 60,
    refreshBeforeSend: true,
    syncProducts: true,
    syncCustomers: false,
    syncProformas: false,
    syncRecentSales: false,
    syncCategories: false,
    pushSalesToInauzwa: false,
    businessName: null,
    defaultPaymentInstructions: null,
    defaultBranchPickupInfo: null,
    lastSyncAt: null,
    lastSyncError: null,
    currency: 'TZS',
    connection: {
      configured: false,
      source: null,
      configuredVia: null,
      databaseUrlMasked: null,
      apiUrl: null,
      hasApiToken: false,
      loginEmail: null,
      connectedViaLogin: false,
      vendorAutoFromLogin: false,
    },
    lastSyncResult: null,
  },
};
